### ISSUE TITLE
not able to read csv

### ISSUE THREAD

**Issue by mpk-inst-in** [sayakpaul/Manning-Phishing-Websites-Detection#1]
Hi sayakpaul,

I am not able to do a read_csv on this file (phishing_ds= pd.read_csv('Phishing.csv')). Using google colab environment. I am getting the following error: 

"ParserError: Error tokenizing data. C error: Expected 1 fields in line 94, saw 2"

Would be great to know why this could be happening.

Cheers!!

**Comment by sayakpaul** [comment]
It might be a pandas issue because on my end I do not face such an error. I am using a Colab Notebook, btw.
