### ISSUE TITLE
Data generation at run time - info only

### ISSUE THREAD

**Issue by mpk-inst-in** [sayakpaul/Manning-Phishing-Websites-Detection#2]
For my info only. Quick question. how is this data generated for an in coming mail ? I reckon you have some tool to dissect the email to generate all the properties present in the dataset.

**Comment by sayakpaul** [comment]
I didn't generate this dataset. The dataset collection process is detailed here: https://archive.ics.uci.edu/ml/datasets/phishing+websites.
